"""create users table

Revision ID: e66f487fe881
Revises: 
Create Date: 2025-09-02 22:27:55.471821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66f487fe881'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('folder_path', sa.Text(), nullable=False),
    sa.Column('upload_time', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps_json', sa.Text(), nullable=True),
    sa.Column('fail_fast', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft','running','succeeded','failed','stopped')", name='ck_run_batch_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_batch_user_id'), 'run_batch', ['user_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audio_chunk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.String(), nullable=True),
    sa.Column('chunk_path', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.String(), nullable=True),
    sa.Column('call_name', sa.String(length=255), nullable=True),
    sa.Column('call_description', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('full_transcript', sa.Text(), nullable=True),
    sa.Column('llm_summary', sa.Text(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=50), nullable=True),
    sa.Column('sentiment_confidence', sa.Float(), nullable=True),
    sa.Column('emotion_label', sa.String(length=50), nullable=True),
    sa.Column('emotion_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_table('run_batch_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('chunk_total', sa.Integer(), nullable=False),
    sa.Column('chunk_done', sa.Integer(), nullable=False),
    sa.Column('chunk_error', sa.Integer(), nullable=False),
    sa.Column('last_progress_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','running','succeeded','failed','skipped')", name='ck_run_batch_call_status'),
    sa.ForeignKeyConstraint(['batch_id'], ['run_batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'call_id', name='ux_run_batch_call_unique')
    )
    op.create_index(op.f('ix_run_batch_call_batch_id'), 'run_batch_call', ['batch_id'], unique=False)
    op.create_index(op.f('ix_run_batch_call_call_id'), 'run_batch_call', ['call_id'], unique=False)
    op.create_table('run_batch_trigger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['run_batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'trigger_id', name='ux_run_batch_trigger_unique')
    )
    op.create_index(op.f('ix_run_batch_trigger_batch_id'), 'run_batch_trigger', ['batch_id'], unique=False)
    op.create_index(op.f('ix_run_batch_trigger_trigger_id'), 'run_batch_trigger', ['trigger_id'], unique=False)
    op.create_table('trigger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('segment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('speaker', sa.String(length=20), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=50), nullable=True),
    sa.Column('sentiment_confidence', sa.Float(), nullable=True),
    sa.Column('emotion_label', sa.String(length=50), nullable=True),
    sa.Column('emotion_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['audio_chunk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trigger_eval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_id'], ['trigger.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('word', sa.Text(), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    op.drop_table('trigger_eval')
    op.drop_table('segment')
    op.drop_table('trigger')
    op.drop_index(op.f('ix_run_batch_trigger_trigger_id'), table_name='run_batch_trigger')
    op.drop_index(op.f('ix_run_batch_trigger_batch_id'), table_name='run_batch_trigger')
    op.drop_table('run_batch_trigger')
    op.drop_index(op.f('ix_run_batch_call_call_id'), table_name='run_batch_call')
    op.drop_index(op.f('ix_run_batch_call_batch_id'), table_name='run_batch_call')
    op.drop_table('run_batch_call')
    op.drop_table('call_data')
    op.drop_table('audio_chunk')
    op.drop_table('user')
    op.drop_index(op.f('ix_run_batch_user_id'), table_name='run_batch')
    op.drop_table('run_batch')
    op.drop_table('call')
    op.drop_table('agent')
    # ### end Alembic commands ###
